name: Mailbox cleanup job CI

on:
  pull_request:

jobs:
  build-test:
    name: Build and Unit Test mailbox cleanup job
    uses: thumperq/cicd/.github/workflows/ci.yaml@v0.1.46
    secrets:
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ vars.VAULT_TOKEN }}
      DOMAIN_NAME: wms
